#!/bin/bash
set -o errexit
set -o nounset
set -o verbose

sbt \
    +test \
    +sprayJsonJVM/mimaReportBinaryIssues

# Automatic publishing for tags that start with `v<digit>`
if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_TAG" =~ ^v[0-9].* ]]; then
    # Setup gpg keys
    gpg --keyserver keyserver.ubuntu.com --recv-keys \
	"DC6A9A5E884B2D680E080467E107A4A6CF561C67" \
	|| echo "WARNING: unable to refresh key; it may be out of date." >&2
    openssl aes-256-cbc \
	    -K "$encrypted_f81da6a1e6e0_key" \
	    -iv "$encrypted_f81da6a1e6e0_iv" \
	    -in .ci/sec.gpg.enc \
	    -out sec.gpg \
	    -d
    gpg --import sec.gpg

    # Setup publishing
    cat <<-EOF > sonatype.sbt
	credentials in Global += Credentials(
	    "GnuPG Key ID",
	    "gpg",
	    "DC6A9A5E884B2D680E080467E107A4A6CF561C67",
	    "ignored"
	)
	credentials in Global += Credentials(
	    "Sonatype Nexus Repository Manager",
	    "oss.sonatype.org",
	    "8VNUX6+2",
	    "$SONATYPE_PASS"
	)
	EOF

    # Build and publish
    sbt \
	+sprayJsonJVM/publish \
	+sprayJsonJS/publish \
	+sprayJsonNative/publish \
	sonatypeRelease
fi
